# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_haversine <- function(lon_x, lat_x, lon_y, lat_y) {
    .Call('_pargeodist_dist_haversine', PACKAGE = 'pargeodist', lon_x, lat_x, lon_y, lat_y)
}

dist_spherical_cosine <- function(lon_x, lat_x, lon_y, lat_y) {
    .Call('_pargeodist_dist_spherical_cosine', PACKAGE = 'pargeodist', lon_x, lat_x, lon_y, lat_y)
}

rcpp_parallel_distm_C_min <- function(x, y, miles) {
    .Call('_pargeodist_rcpp_parallel_distm_C_min', PACKAGE = 'pargeodist', x, y, miles)
}

rcpp_parallel_distm_C <- function(x, y) {
    .Call('_pargeodist_rcpp_parallel_distm_C', PACKAGE = 'pargeodist', x, y)
}

rcpp_distm <- function(x, y) {
    .Call('_pargeodist_rcpp_distm', PACKAGE = 'pargeodist', x, y)
}

